# Methods

We use a latent variable measurement model to identify indicators of PD severity. Latent variable measurement models are generalizations of the method of factor analysis developed to quantify psychological constructs. Factor analysis methods are widely used in the fields of psychology, sociology, and medicine. Factor analysis models assume -- and attempt to develop a statistical model to quantify -- a continuous latent variable (e.g., Parkinson’s Disease severity) is responsible for the covariation observed among various signs and symptoms. We have used these methods to quantify severity in Alzheimer’s disease (Gross et al, 2016). The generalization we use is implemented with Mplus software (Muthén & Muthén, Los Angeles, CA). We use categorical latent variable modeling technique known as factor mixture models to detect subtypes of PD. Factor mixture models are generalizations of classification methods known as K-means clustering, latent class analysis, and factor analysis, and are appropriate when the source of heterogeneity (i.e., membership PD sub-type groups) is unknown and the indicators of subtype group membership are a mix of continuous and categorical variables (Lubke, & Muthén, 2005).

