
# Impact of the analysis

Using only clinical markers (UPDRS II & III, MoCA, and SCOPA-AUT) from the PPMI database, we demonstrated reliable subcategorization of PD patients into subclasses based on disease severity. We demonstrated a continuous latent variable is responsible for the covariation observed among various signs and symptoms and use this to subcategorize patients into subgroups with distinct symptom profiles. We presented the relative importance of the symptom to the general trait and defined 4 classes, or symptom patterns. We demonstrated major differences in classes 1 and 4 in autonomic dysfunction; the former having low levels of autonomic involvement and the latter with pronounced symptoms in this domain. Classes 2 and 3 represented varying degrees of symptom burden but were qualitatively similar. Our model also suggests that in a patient sample similar to the PPMI database, the most common latent class would be class 3 (69%, slowly progressing over time) followed class 2 (19%, more rapidly progressing). This is similar to the pattern of progression seen in clinical experience. Given that our analyses were based on a limited sample of 200 PD patients followed for 5 years longitudinally in the PPMI database, validation of these models in larger longitudinal cohorts is needed.
